project_id = "jnnglznnickmxwdrnrwh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.voice-interview]
verify_jwt = true

[studio]
enabled = true
port = 54323

[functions.gemini-resume-analysis]
enabled = true
verify_jwt = true
import_map = "./functions/gemini-resume-analysis/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/gemini-resume-analysis/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/gemini-resume-analysis/*.html" ]