// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnnglznnickmxwdrnrwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impubmdsem5uaWNrbXh3ZHJucndoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTQxNTgsImV4cCI6MjA2ODY5MDE1OH0.j_lP0rW41T6-QNBpJjfJxiiintD5I-Y9jGpjZ6DR5jw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});